version: '3.3'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.1'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xms2g -Xmx2g'
    networks:
      - esnet
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.2.1'
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    networks:
      - esnet
networks:
  esnet:
    driver: bridge
